In [149]:
import pandas as pd
pd.set_option('display.max_columns',None)
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from scipy.stats import f,pearsonr,spearmanr
from sklearn.preprocessing import MinMaxScaler,StandardScaler
import warnings
warnings.filterwarnings('ignore')
from sklearn.feature_selection import RFE

In [124]:
data_cars = pd.read_csv('cleaned_corolla_data')
data_cars.head()

,Unnamed: 0,Id,Price,Age_08_04,KM,HP,Met_Color,Automatic,cc,Doors,Cylinders,Gears,Quarterly_Tax,Weight,Mfr_Guarantee,BOVAG_Guarantee,Guarantee_Period,ABS,Airbag_1,Airbag_2,Airco,Automatic_airco,Boardcomputer,CD_Player,Central_Lock,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Tow_Bar,Fuel_Type_Diesel,Fuel_Type_Petrol
0,0,1,13500,23,46986,90,1,0,2000,3,4,5,210,1165,0,1,3,1,1,1,0,0,1,0,1,1,1,0,0,0,1,0,0,0,1,0
1,1,2,13750,23,72937,90,1,0,2000,3,4,5,210,1165,0,1,3,1,1,1,1,0,1,1,1,0,1,0,0,0,1,0,0,0,1,0
2,2,3,13950,24,41711,90,1,0,2000,3,4,5,210,1165,1,1,3,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0
3,3,4,14950,26,48000,90,0,0,2000,3,4,5,210,1165,1,1,3,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0
4,4,5,13750,30,38500,90,0,0,2000,3,4,5,210,1170,1,1,3,1,1,1,1,0,1,0,1,1,1,0,1,0,1,0,0,0,1,0

In [115]:
data_cars.columns

Index(['Unnamed: 0', 'Id', 'Price', 'Age_08_04', 'KM', 'HP', 'Met_Color',
       'Automatic', 'cc', 'Doors', 'Cylinders', 'Gears', 'Quarterly_Tax',
       'Weight', 'Mfr_Guarantee', 'BOVAG_Guarantee', 'Guarantee_Period', 'ABS',
       'Airbag_1', 'Airbag_2', 'Airco', 'Automatic_airco', 'Boardcomputer',
       'CD_Player', 'Central_Lock', 'Powered_Windows', 'Power_Steering',
       'Radio', 'Mistlamps', 'Sport_Model', 'Backseat_Divider', 'Metallic_Rim',
       'Radio_cassette', 'Tow_Bar', 'Fuel_Type_Diesel', 'Fuel_Type_Petrol'],
      dtype='object')

In [125]:
data_cars.drop(labels=['Unnamed: 0','Id'],axis=1,inplace=True)
data_cars.head()

,Price,Age_08_04,KM,HP,Met_Color,Automatic,cc,Doors,Cylinders,Gears,Quarterly_Tax,Weight,Mfr_Guarantee,BOVAG_Guarantee,Guarantee_Period,ABS,Airbag_1,Airbag_2,Airco,Automatic_airco,Boardcomputer,CD_Player,Central_Lock,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Tow_Bar,Fuel_Type_Diesel,Fuel_Type_Petrol
0,13500,23,46986,90,1,0,2000,3,4,5,210,1165,0,1,3,1,1,1,0,0,1,0,1,1,1,0,0,0,1,0,0,0,1,0
1,13750,23,72937,90,1,0,2000,3,4,5,210,1165,0,1,3,1,1,1,1,0,1,1,1,0,1,0,0,0,1,0,0,0,1,0
2,13950,24,41711,90,1,0,2000,3,4,5,210,1165,1,1,3,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0
3,14950,26,48000,90,0,0,2000,3,4,5,210,1165,1,1,3,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0
4,13750,30,38500,90,0,0,2000,3,4,5,210,1170,1,1,3,1,1,1,1,0,1,0,1,1,1,0,1,0,1,0,0,0,1,0

In [126]:
data_cars['Cylinders'].unique()

array([4])

In [127]:
del data_cars['Cylinders']

In [128]:
data_cars.head()

,Price,Age_08_04,KM,HP,Met_Color,Automatic,cc,Doors,Gears,Quarterly_Tax,Weight,Mfr_Guarantee,BOVAG_Guarantee,Guarantee_Period,ABS,Airbag_1,Airbag_2,Airco,Automatic_airco,Boardcomputer,CD_Player,Central_Lock,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Tow_Bar,Fuel_Type_Diesel,Fuel_Type_Petrol
0,13500,23,46986,90,1,0,2000,3,5,210,1165,0,1,3,1,1,1,0,0,1,0,1,1,1,0,0,0,1,0,0,0,1,0
1,13750,23,72937,90,1,0,2000,3,5,210,1165,0,1,3,1,1,1,1,0,1,1,1,0,1,0,0,0,1,0,0,0,1,0
2,13950,24,41711,90,1,0,2000,3,5,210,1165,1,1,3,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0
3,14950,26,48000,90,0,0,2000,3,5,210,1165,1,1,3,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0
4,13750,30,38500,90,0,0,2000,3,5,210,1170,1,1,3,1,1,1,1,0,1,0,1,1,1,0,1,0,1,0,0,0,1,0

## removing outliers using percentile method

In [129]:
print(data_cars.shape)
upper_limit = data_cars['Price'].quantile(0.90)
lower_limit = data_cars['Price'].quantile(0.05)

f1 = data_cars['Price'] < upper_limit
f2 = data_cars['Price'] > lower_limit

data = data_cars[f1 & f2]

data.shape

(1436, 33)

(1202, 33)

In [130]:
data.isna().sum()

Price               0
Age_08_04           0
KM                  0
HP                  0
Met_Color           0
Automatic           0
cc                  0
Doors               0
Gears               0
Quarterly_Tax       0
Weight              0
Mfr_Guarantee       0
BOVAG_Guarantee     0
Guarantee_Period    0
ABS                 0
Airbag_1            0
Airbag_2            0
Airco               0
Automatic_airco     0
Boardcomputer       0
CD_Player           0
Central_Lock        0
Powered_Windows     0
Power_Steering      0
Radio               0
Mistlamps           0
Sport_Model         0
Backseat_Divider    0
Metallic_Rim        0
Radio_cassette      0
Tow_Bar             0
Fuel_Type_Diesel    0
Fuel_Type_Petrol    0
dtype: int64

## Standardising data

In [121]:
# temp_data = data.drop(labels='Price',axis=1)
# col = temp_data.columns
# std_sclr = MinMaxScaler()
# d = pd.DataFrame(std_sclr.fit_transform(temp_data),columns=col)
# data.iloc[:,1:] =d

# print(data.shape)

# data.head()

(1202, 33)

,Price,Age_08_04,KM,HP,Met_Color,Automatic,cc,Doors,Gears,Quarterly_Tax,Weight,Mfr_Guarantee,BOVAG_Guarantee,Guarantee_Period,ABS,Airbag_1,Airbag_2,Airco,Automatic_airco,Boardcomputer,CD_Player,Central_Lock,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Tow_Bar,Fuel_Type_Diesel,Fuel_Type_Petrol
0,13500,0.149254,0.193355,0.446809,1.0,0.0,1.0,0.333333,0.666667,1.0,0.268293,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,13750,0.149254,0.300149,0.446809,1.0,0.0,1.0,0.333333,0.666667,1.0,0.268293,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,13950,0.164179,0.171647,0.446809,1.0,0.0,1.0,0.333333,0.666667,1.0,0.268293,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,14950,0.194030,0.197528,0.446809,0.0,0.0,1.0,0.333333,0.666667,1.0,0.268293,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,13750,0.253731,0.158433,0.446809,0.0,0.0,1.0,0.333333,0.666667,1.0,0.276423,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

## train test split functions

In [131]:
print(data.shape)
def intialize_X_tain_y_train():
    # split into input and output elements
    X = data.drop(labels='Price',axis=1)
    y = data[['Price']]
    # summarize the shape of the dataset
    print(X.shape, y.shape)
    # split into train and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=20)
    # summarize the shape of the train and test sets
    return X_train, X_test, y_train, y_test
    
X_train, X_test, y_train, y_test = intialize_X_tain_y_train()
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(1202, 33)
(1202, 32) (1202, 1)
(1021, 32) (181, 32) (1021, 1) (181, 1)

## model creation methods

In [132]:
def get_RandomForest_mae_mse(X_train,y_train):
    rf_model = RandomForestRegressor()
    rf_model.fit(X_train,y_train)
    rf_pred = rf_model.predict(X_test)
    rf_mae = mean_absolute_error(y_test,rf_pred)
    rf_mse = mean_squared_error(y_test,rf_pred)
    return rf_mae,rf_mse

def get_GradientBoosting_mae_mse(X_train,y_train):
    gb_model = GradientBoostingRegressor()
    gb_model.fit(X_train,y_train)
    gb_pred = gb_model.predict(X_test)
    gb_mae = mean_absolute_error(y_test,gb_pred)
    gb_mse = mean_squared_error(y_test,gb_pred)
    return gb_mae,gb_mse

# 1. Feature slection
## 1.1 Filter Method
### 1.1.1 feature selection using Pearsons correlation coeff

In [133]:
data.shape

(1202, 33)

In [134]:
temp_data = data.drop(labels='Price',axis=1)

In [135]:
corr = temp_data.corr()

In [136]:
corr.shape[0]

32

In [137]:
columns = np.full((corr.shape[0],), True, dtype=bool)
for i in range(corr.shape[0]):
    for j in range(i+1, corr.shape[0]):
        if np.abs(corr.iloc[i,j]) >= 0.9:
            if columns[j]:
                columns[j] = False
selected_columns = temp_data.columns[columns]

In [138]:
[x for x in temp_data.columns if x not in selected_columns]

['Radio_cassette', 'Fuel_Type_Petrol']

In [139]:
X = data[selected_columns]
y = data['Price']

    
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.15,shuffle=True,random_state=23)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(1021, 30) (181, 30) (1021,) (181,)

## building models using selected features

In [140]:
rf_mae1,rf_mse1 = get_RandomForest_mae_mse(X_train,y_train)
rf_mae1,rf_mse1

(700.6572928176796, 844766.1679850828)

In [141]:
gb_mae1,gb_mse1 = get_GradientBoosting_mae_mse(X_train,y_train)
gb_mae1,gb_mse1

(699.9136786653271, 812823.7912796001)

## Using Pearsonr and Spearmanr from scipy

In [142]:
data.shape

(1202, 33)

In [143]:
data.head()

,Price,Age_08_04,KM,HP,Met_Color,Automatic,cc,Doors,Gears,Quarterly_Tax,Weight,Mfr_Guarantee,BOVAG_Guarantee,Guarantee_Period,ABS,Airbag_1,Airbag_2,Airco,Automatic_airco,Boardcomputer,CD_Player,Central_Lock,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Tow_Bar,Fuel_Type_Diesel,Fuel_Type_Petrol
0,13500,23,46986,90,1,0,2000,3,5,210,1165,0,1,3,1,1,1,0,0,1,0,1,1,1,0,0,0,1,0,0,0,1,0
1,13750,23,72937,90,1,0,2000,3,5,210,1165,0,1,3,1,1,1,1,0,1,1,1,0,1,0,0,0,1,0,0,0,1,0
2,13950,24,41711,90,1,0,2000,3,5,210,1165,1,1,3,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0
3,14950,26,48000,90,0,0,2000,3,5,210,1165,1,1,3,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0
4,13750,30,38500,90,0,0,2000,3,5,210,1170,1,1,3,1,1,1,1,0,1,0,1,1,1,0,1,0,1,0,0,0,1,0

In [144]:
data['ABS'].unique()

array([1, 0])

In [145]:
# Declare predictor(X) and dependent variable(y) for regression problem (suffix '_reg')
y_reg = data['Price']
X_category_reg = data.loc[:,['Met_Color','cc','Doors','Gears','Mfr_Guarantee','BOVAG_Guarantee'
                                       ,'Guarantee_Period','ABS','Airbag_1','Airbag_2','Airco',
                                       'Automatic_airco','Boardcomputer','CD_Player','Central_Lock',
                                       'Central_Lock','Powered_Windows','Power_Steering','Radio',
                                       'Mistlamps','Sport_Model','Backseat_Divider','Metallic_Rim',
                                       'Radio_cassette','Tow_Bar','Fuel_Type_Diesel','Fuel_Type_Petrol']]
X_numeric_reg = data.loc[:,['Age_08_04','KM','HP','Quarterly_Tax','Weight']]

# Check for missing values
assert X_category_reg.isnull().any().any() == False
assert X_numeric_reg.isnull().any().any() == False

In [146]:
def f_test(X, y, target, mode):
    
    # Do F-test using Pearson correlation
    if mode.lower() == 'pearsonr':
        
        temp = []
        for col in X.columns:
            corr, _ = pearsonr(X[col].values, y)
            temp.append(corr)

        df = pd.DataFrame(temp, columns=['pearsonr'], index=X.columns)
    
    
    # Do F-test using Pearson's rank correlation
    elif mode.lower() == 'spearmanr':
        
        corr, _ = spearmanr(X, y_reg)
        df = pd.DataFrame(corr[:-1,-1], columns=['spearman'], index=X.columns)
        
    else:
        return
    
    degree_of_freedom = len(y)-2
    df['F-score'] = df.iloc[:,0].apply(lambda x: x**2/(1-x**2)*degree_of_freedom)
    df['p-value'] = f.sf(df['F-score'], 1, degree_of_freedom)
    return df

In [147]:
f_test(X_numeric_reg, y_reg, target='Price', mode='pearsonr')

               pearsonr      F-score        p-value
Age_08_04     -0.820485  2471.914916  1.050015e-293
KM            -0.441849   291.109659   1.313730e-58
HP             0.161443    32.113495   1.819590e-08
Quarterly_Tax  0.083134     8.351131   3.923810e-03
Weight         0.228488    66.099189   1.059681e-15

## we can use sklearn.feature_selection.f_regression which is done exactly the same thing: compute correlation and do F-test.

In [66]:
from sklearn.feature_selection import f_regression

In [67]:
F_score, p_value = f_regression(X_numeric_reg, y_reg)
df = pd.DataFrame(list(zip(X_numeric_reg.columns, F_score, p_value)), 
                  columns=['feature', 'F-score', 'p-value'])
df.set_index('feature')

                   F-score        p-value
feature
Age_08_04      2471.914916  1.050015e-293
KM              291.109659   1.313730e-58
HP               32.113495   1.819590e-08
Quarterly_Tax     8.351131   3.923810e-03
Weight           66.099189   1.059681e-15

**seems like Quaterly_tax has very less correlation with target compared to others

## 1.2 . Wrapper Method
### Recursive feature elimination (RFE)

In [154]:
data.head()

,Price,Age_08_04,KM,HP,Met_Color,Automatic,cc,Doors,Gears,Quarterly_Tax,Weight,Mfr_Guarantee,BOVAG_Guarantee,Guarantee_Period,ABS,Airbag_1,Airbag_2,Airco,Automatic_airco,Boardcomputer,CD_Player,Central_Lock,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Tow_Bar,Fuel_Type_Diesel,Fuel_Type_Petrol
0,13500,23,46986,90,1,0,2000,3,5,210,1165,0,1,3,1,1,1,0,0,1,0,1,1,1,0,0,0,1,0,0,0,1,0
1,13750,23,72937,90,1,0,2000,3,5,210,1165,0,1,3,1,1,1,1,0,1,1,1,0,1,0,0,0,1,0,0,0,1,0
2,13950,24,41711,90,1,0,2000,3,5,210,1165,1,1,3,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0
3,14950,26,48000,90,0,0,2000,3,5,210,1165,1,1,3,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0
4,13750,30,38500,90,0,0,2000,3,5,210,1170,1,1,3,1,1,1,1,0,1,0,1,1,1,0,1,0,1,0,0,0,1,0

In [156]:
data.shape

(1202, 33)

In [155]:
X,y = data.drop(labels='Price',axis=1),data[['Price']]

In [163]:
def do_RFE(X,y,estimator,n):
    rfe = RFE(estimator, n_features_to_select=n).fit(X, y)
    X = rfe.transform(X)
    return X

selected_X = do_RFE(X,y, RandomForestRegressor(),20)
print(selected_X.shape)

(1202, 20)

In [165]:
selected_X.shape,y.shape

((1202, 20), (1202, 1))

In [166]:
X_train, X_test, y_train, y_test = train_test_split(selected_X,y,test_size=0.15,shuffle=True,random_state=23)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(1021, 20) (181, 20) (1021, 1) (181, 1)

## building models

In [167]:
rf_mae2,rf_mse2 = get_RandomForest_mae_mse(X_train,y_train)
rf_mae2,rf_mse2

(721.0890055248619, 885669.2812668507)

In [168]:
gb_mae1,gb_mse1 = get_GradientBoosting_mae_mse(X_train,y_train)
gb_mae1,gb_mse1

(703.3441055335489, 816751.7642075185)

## lets try with 25 features

In [177]:
X.shape,y.shape

((1202, 32), (1202, 1))

In [178]:
selected_X = do_RFE(X,y, RandomForestRegressor(),25)
print(selected_X.shape)

(1202, 25)

In [179]:
X_train, X_test, y_train, y_test = train_test_split(selected_X,y,test_size=0.15,shuffle=True,random_state=23)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(1021, 25) (181, 25) (1021, 1) (181, 1)

## building models

In [180]:
rf_mae3,rf_mse3 = get_RandomForest_mae_mse(X_train,y_train)
rf_mae3,rf_mse3

(711.8303314917127, 866564.362735359)

In [181]:
gb_mae3,gb_mse3 = get_GradientBoosting_mae_mse(X_train,y_train)
gb_mae3,gb_mse3

(697.5463617362612, 817939.3945781409)

## trying iwth 27 features

In [204]:
X.shape,y.shape

((1202, 32), (1202, 1))

In [205]:
selected_X = do_RFE(X,y, RandomForestRegressor(),27)
print(selected_X.shape)

(1202, 27)

In [206]:
X_train, X_test, y_train, y_test = train_test_split(selected_X,y,test_size=0.15,shuffle=True,random_state=23)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(1021, 27) (181, 27) (1021, 1) (181, 1)

## building models

In [207]:
rf_mae4,rf_mse4 = get_RandomForest_mae_mse(X_train,y_train)
rf_mae4,rf_mse4

(708.3832596685082, 837332.4731276243)

In [208]:
gb_mae4,gb_mse4 = get_GradientBoosting_mae_mse(X_train,y_train)
gb_mae4,gb_mse4

(696.7581583946085, 809202.1942781984)